config/routes.rb
Rails.application.routes.draw do
devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_scope :user do
  post '/homes/guest_sign_in', to: 'user/homes#guest_sign_in'
end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

root to: "user/homes#top"
get '/about' => "user/homes#about", as:"about"

namespace :admin do
  root to: 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :areas, only: [:index, :create, :edit, :update, :destroy]
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :posts, only: [:index, :show, :edit, :update] do
    resources :reviews, only: [:create, :destroy, :index, :show, :update]
  end
end

scope module: :user do
  resources :posts do
    resources :reviews, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  get "users/unsubscribe" => "users#unsubscribe", as:"unsubscribe"
  patch "users/withdraw" => "users#withdraw", as:"withdraw"

  resources :users, only: [:show, :edit, :update] do
    resources :bookmarks, only: [:index, :create, :destroy]
    collection do
      get "users/complete" => "users#complete", as:"complete"
    end
  end

  resources :genres, only: [:show]
  resources :areas, only: [:show]

  get "search" => "searches#search"
  post "filter" => "searches#filter", as: "filter"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :posts
 
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
  # 一つのユーザーは同じ投稿に対して一回しかブックマークができませんというバリデーション
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  belongs_to :area
  has_many :tags
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many_attached :images, dependent: :destroy
  
  validates :playground, presence: true
  validates :title, presence: true
  validates :text, presence: true
  validates :genre_id, presence: true
  validates :area_id, presence: true
  validates :images, presence: true


  def get_image
    unless images.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    images
  end
  
  def bookmark_by?(user)
    bookmarks.exists?(user_id: user.id)
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
  
  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  has_one_attached :profile_image, dependent: :destroy
  
  validates :full_name, presence: true
  validates :user_name, presence: true
   
   def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
        user.full_name = "ゲストユーザー"
        user.user_name = "guest_user"
        user.password = SecureRandom.urlsafe_base64
    end
   end

   def get_profile_image(width, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
     profile_image.variant(resize_to_limit: [width, height]).processed
   end
   
   def bookmark_by?(post)
     self.bookmarks.exists?(post_id: post.id)
   end
   
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end
  
  def new
    @genre = Genre.new
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "更新しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  def destroy
    @genre =Genre.find(params[:id])
    @genre.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
    
    def show
        @genre = Genre.find(params[:id])
    end
end

app/helpers/admin/areas_helper.rb
module Admin::AreasHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/areas_helper.rb
module User::AreasHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/genres/edit.html.erb
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h4 class="font-weight-normal mt-3">ジャンル情報編集中•••</h4>
    </div>
     <p>
       <div class="row justify-content-center">
          <%= form_with model: @genre, url: admin_genre_path, method: :patch, local:true do |f| %>
            <tr>
              <td style="width: 30%"><%= f.label :name, "ジャンル名", class:'col-md-5 col-form-label' %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            
            <td><%= f.submit '変更を保存', class: 'btn btn-sm btn-success ml-auto' %></td>
            <td></td>
            <td><%= link_to '削除する', @genre, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger ml-auto"%></td>
          <% end %>
       </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row" style="margin-top:25px;">
  <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <h2><span class="bg-light">ジャンル一覧・追加<span></h2>
      </div>
      <div class="mt-4">
        <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
          <div class="form-group mb-5">
              <%= f.label :"ジャンル名" %>
              <%= f.text_field :name, placeholder: "ジャンル名" %>
              <%= f.submit '新規登録', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>


       <div class="col-sm-7 px-sm-0 mx-auto mb-5">
        <table class="table table-hover">
         <thead class="table-active">
         <tr>
          <th></th>
          <th>ジャンル</th>
          <th colspan="3"></th>
        </tr>
          </thead>
        <tbody>
         <% @genres.each do |genre| %>
         <tr>
           <td><%= genre.name %></td>
           <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class: 'btn btn-sm btn-success' %></td>
         </tr>
       <% end %>
   </tbody>
</table>