config/routes.rb
Rails.application.routes.draw do
devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_scope :user do
  post '/homes/guest_sign_in', to: 'user/homes#guest_sign_in'
end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

root to: "user/homes#top"
get '/about' => "user/homes#about", as:"about"

namespace :admin do
  root to: 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :areas, only: [:index, :create, :edit, :update, :destroy]
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :posts, only: [:index, :show, :edit, :update] do
    resources :reviews, only: [:create, :destroy, :index, :show, :update]
  end
end

scope module: :user do
  resources :posts do
    resources :reviews, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  get "users/unsubscribe" => "users#unsubscribe", as:"unsubscribe"
  patch "users/withdraw" => "users#withdraw", as:"withdraw"

  resources :users, only: [:show, :edit, :update] do
    resources :bookmarks, only: [:index, :create, :destroy]
    collection do
      get "users/complete" => "users#complete", as:"complete"
    end
  end

  resources :genres, only: [:show]
  resources :areas, only: [:show]

  get "search" => "searches#search"
  post "filter" => "searches#filter", as: "filter"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  has_one_attached :profile_image, dependent: :destroy
  
  validates :full_name, presence: true
  validates :user_name, presence: true
   
   def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
        user.full_name = "ゲストユーザー"
        user.user_name = "guest_user"
        user.password = SecureRandom.urlsafe_base64
    end
   end

   def get_profile_image(width, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
     profile_image.variant(resize_to_limit: [width, height]).processed
   end
   
   def bookmark_by?(post)
     self.bookmarks.exists?(post_id: post.id)
   end
   
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @post = Post.find(params[:id])
    @posts = @user.posts
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] =  "更新しました！"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
    
    private

  def user_params
    params.require(:user).permit(:full_name, :user_name, :profile_image)
  end
  
end

app/controllers/user/areas_controller.rb
class User::AreasController < ApplicationController
  
  def show
    @area = Area.find(params[:id])
  end
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController

  def create
    @bookmark = current_user.bookmarks.new(post_id: params[:post_id])
    @bookmark.save
    @post = Post.find(params[:post_id])
  end

  def destroy
    @post= Post.find(params[:post_id])
    @bookmark = current_user.bookmarks.find_by(post_id: @post.id)
    @bookmark.destroy
  end

  def index
    @bookmarks = current_user.bookmarks.includes(:post)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
    
    def show
        @genre = Genre.find(params[:id])
    end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
  end

  def about
    @posts = Post.all.order(created_at: :desc)
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'guestuserでログインしました。'
  end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]



  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "投稿が成功しました"
      
      # visionAPI導入時以下使用
      # tags = Vision.get_image_data(@post.images.first)
      # tags.each do |tag|
      #   p '-------'
      #   p tag
      #   p '-------'
      #   # @post.tags.create(name: tag)
      # end
      
      redirect_to post_path(@post)
    else
      @posts = Post.all
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @review= Review.new
    @reviews = @post.reviews.where(visible: true)
  end

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
    @post_genre = @posts.where(genre: params[:genre])
    @genre_name = params[:genre_name]

  end


  def edit
  end

  def update
    @post= Post.find(params[:id])
    if @post.update(post_params)
       flash[:notice] = "更新しました"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post =Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to user_path(current_user)
  end


  private

  def post_params
    params.require(:post).permit(:playground, :title, :text, :genre_id, :area_id, images: [] )
  end

  def ensure_correct_user
    @post= Post.find(params[:id])
    unless @post.user == current_user
      redirect_to post_path(@post.id)
    end
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true
class User::RegistrationsController < Devise::RegistrationsController
  #before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    posts_path
  end
  
   protected
  #新規会員登録時にパラメーターでDBへ保存するデータを指定する
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :full_name, :user_name]) 
  end


  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @review= Review.new
    @reviews = @post.reviews.where(visible: true)
    comment = current_user.reviews.new(review_params)
    comment.post_id = @post.id
    comment.comment_score = Language.get_data(review_params[:comment])
    comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @review= Review.new
    @reviews = @post.reviews.where(visible: true)
    Review.find_by(id: params[:id], post_id: params[:post_id]).destroy
  end

  def index
    @comments = Comment.all
  end

  private

  def review_params
    params.require(:review).permit(:comment, :score)
  end

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController

  def search
    @posts = Post.all
    @genres = Genre.all
    @post = params[:name].present? ? Genre.find(params[:name]).posts : Post.all
    @areas = Area.all
  end

  def filter
    @genres = Genre.all
    @areas = Area.all

    if params[:keyword].present?
      @posts = Post.where("text like ?", "%" + params[:keyword] + "%")
    else
      @posts = Post.all
    end
    render :search
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    posts_path
   
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
  end


  def user_state
   @user = User.find_by(email: params[:user][:email])
   return if !@user
   if @user.valid_password?(params[:user][:password]) && @user.is_deleted
     flash[:notice] = "退会済みです。再度ご登録をお願い致します。"
     redirect_to new_user_session_path
   else
     user_session_path
   end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  

  def show
    @user = User.find(current_user.id)
    @posts = @user.posts
  end

  def index
    @bookmarks = current_user.bookmarks.includes(:post)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] =  "更新しました！"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def unsubscribe
  end 
  
  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行しました！"
    redirect_to root_path
  end

    private

  def user_params
    params.require(:user).permit(:full_name, :user_name, :profile_image)
  end
  
  def ensure_correct_user
    @user= User.find(params[:id])
    unless @user == current_user
      redirect_to posts_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/areas_helper.rb
module User::AreasHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/views/admin/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100, 100) %></tr>
  <tr>
	  <th>full name</th>
	  <th><%= user.full_name %></th>
  </tr>
  <tr>
	  <th>user name</th>
	  <th><%= user.user_name %></th>
  </tr>
</table>

app/views/admin/users/edit.html.erb
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h4 class="font-weight-normal mt-3"><%= @user.user_name %>さんの会員情報編集</h4>
    </div>
        <p><div class="row justify-content-center">
            <%= form_with model: @user do |f| %>
              <tr>
                <td style="width: 30%"><%= f.label :id,"会員ID", class:'col-md-5 col-form-label'%></td> 
                <td><%= @user.id %></td>
              </tr>
              
              <div class="form-group row">
                <%= f.label :full_name, class:'col-md-5 col-form-label'%><br>
                <%= f.text_field :full_name, autofocus: true, autocomplete: "name" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :user_name, class:'col-md-5 col-form-label' %><br>
                <%= f.text_field :user_name, autofocus: true, autocomplete: "name" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :profile_image, '写真', class: 'col-md-4 col-form-label' %>
                <div class="col-md-6">
                  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/jpg, image/png" %>
                </div>
              </div>
              
              <td style="width: 30%"><%= f.label :is_deleted,"会員ステータス", class:'col-md-5 col-form-label'%></td>
                <td>
                  <%= f.radio_button :is_deleted, :false %><%= f.label :is_deleted, "有効" %>&emsp;
                  <%= f.radio_button :is_deleted, :true %><%= f.label :is_deleted, "退会" %>
                </td>
              
              <div class="form-group row">
                <div class="col-md-6 offset-md-4">
                  <%= f.submit '変更を保存', class: "btn btn-success btn-sm" %>
                </div>
              </div>
              
            
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-11 col-lg-8  mx-auto">
   <br>
     <h4><span class="bg-light">会員一覧<span></h4>
      <table class='table'>
       <thead class="table table-light">
        <tr>
          <th>user ID</th>
          <th>user name</th>
          <th>full name</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
       </thead>
         <tbody>
           <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to (user.user_name), admin_user_path(user.id) %></td>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><% if user.is_deleted %>
                    <div class="text-danger">退会済</div>
                  <% else %>
                    <div class="text-success">有効会員</div>
                  <% end %>
              </td>
            </tr>
           <% end %>
　       </tbody>
      </table>
    <!--<div class="col-md-5 mx-auto"><%#= paginate @customers %></div>-->
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-8'>
      <h2><%= @user.user_name %>さんの会員情報</h2>
        <p><%= link_to "会員プロフィールを管理する", edit_admin_user_path(@user), class: "btn btn-sm btn-success" %></p>
      　　　<%= render 'info', user: @user %>
      <h2 class="mt-3"><%= @user.user_name %>さんの投稿</h2>
      
         <%= render 'admin/posts/index', posts: @posts %>
    </div>
  </div>
</div>